CREATE TABLE IF NOT EXISTS visitors (
  monthPrimary varchar(5) NOT NULL PRIMARY KEY,
  visitors int(11) NOT NULL DEFAULT 0,
  visits int(11) NOT NULL DEFAULT 0,
  pages int(11) NOT NULL DEFAULT 0,
  article_views int(11) NOT NULL DEFAULT 0,
  simplify_cefr_a1 int(11) NOT NULL DEFAULT 0,
  simplify_cefr_a2 int(11) NOT NULL DEFAULT 0,
  simplify_cefr_b1 int(11) NOT NULL DEFAULT 0,
  simplify_cefr_b2 int(11) NOT NULL DEFAULT 0,
  simplify_cefr_c1 int(11) NOT NULL DEFAULT 0,
  simplify_grade_1 int(11) NOT NULL DEFAULT 0,
  simplify_grade_2 int(11) NOT NULL DEFAULT 0,
  simplify_grade_3 int(11) NOT NULL DEFAULT 0,
  simplify_grade_4 int(11) NOT NULL DEFAULT 0,
  simplify_grade_5 int(11) NOT NULL DEFAULT 0,
  simplify_grade_6 int(11) NOT NULL DEFAULT 0,
  simplify_grade_7 int(11) NOT NULL DEFAULT 0,
  simplify_grade_8 int(11) NOT NULL DEFAULT 0,
  simplify_grade_9 int(11) NOT NULL DEFAULT 0,
  chats int(11) NOT NULL DEFAULT 0,
  chat_questions int(11) NOT NULL DEFAULT 0,
  translations int(11) NOT NULL DEFAULT 0
);
