export default {
  eyebrow: 'Teaching & media literacy',
  title: 'ai-pedia in the Classroom',
  lead: 'Researching and Learning with Wikipedia’s Curated Knowledge',
  introduction:
    'ai-pedia is more than a simplification tool. It is a research environment that makes Wikipedia’s curated knowledge usable for teaching. The texts it produces are linguistically accessible, its sources are clearly displayed, and it can be used for any subject. This page shows how ai-pedia can be best used, the added value it offers compared to free internet research, and how to design an initial, hands-on introductory lesson that works for any subject.',
  subjects: {
    title: 'Usable in Every Subject',
    introduction:
      'ai-pedia is a tool that can be used for virtually any subject-specific teaching approach. Competent handling of information, sources, and AI is a vitally important cross-curricular, forward-looking key competency. It can be used wherever non-fiction texts are part of the work. Examples by subject area:',
    items: {
      mint: {
        title: 'Science, Technology, Engineering and Mathematics (STEM)',
        body: 'Presenting technical terms and concepts in an understandable way, unpacking scientific phenomena, and providing an insight into structured data.',
      },
      society: {
        title: 'History, Geography and Social Studies',
        body: 'Researching historical, geographical, political, and social topics and making them accessible in an age-appropriate way.',
      },
      arts: {
        title: 'Art, Music and Design',
        body: 'Researching works, people, and techniques, and using freely licensed images for students’ own projects.',
      },
      everyday: {
        title: 'Economics, Home Economics and Everyday Life',
        body: 'Looking up and sorting topics related to consumption, nutrition, money, and life management.',
      },
      languages: {
        title: 'Languages (first and foreign)',
        body: 'ai-pedia provides a source of authentic texts for first and foreign language learning. It supports reading comprehension and textual competence, vocabulary building, and the application of reading strategies. The different language versions of an article also make it possible to compare languages.',
      },
      media: {
        title: 'Media Literacy',
        body: 'In media education – and indeed all subjects – ai-pedia fosters information and research competency. Learners practice criticising sources, assessing their credibility and trustworthiness, checking evidence, and distinguishing fact from opinion using transparent and curated content.',
      },
    },
    differentiation:
      'Thanks to ai-pedia’s ability to flexibly adjust text length and language level, it can be used with students of all levels, from weak to strong readers. In this way it significantly contributes to both individualization and differentiated instruction. Furthermore, the simplification feature means it can even be used by older primary school children.',
  },
  benefits: {
    title: 'Why ai-pedia? The Added Value Compared to Free Internet Research',
    introduction:
      'A quick internet search or an AI-generated summary delivers results instantly but often from an unclear source, influenced by advertising, or even made up entirely. ai-pedia works in a fundamentally different way.',
    items: {
      curated: {
        title: 'Curated, vetted texts',
        body: 'The content generated by ai-pedia is always pulled from a genuine Wikipedia article which has been written by a person who is duty bound to cite their sources. The texts go through quality assurance and are written from a neutral point of view. No thrown-together search results and no advertising.',
      },
      traceable: {
        title: 'Every piece of information can be traced back to its original source',
        body: 'The reading assistant shows the supporting evidence from the original article directly alongside its answers. This lets students see where a statement comes from, trace it back to its origin, and verify it themselves – source criticism put into practice instead of blind trust.',
      },
      independent: {
        title: 'Building knowledge without a personalized algorithm, completely ad-free',
        body: 'Learners build knowledge on their own terms, without being steered by an algorithm: no tracking, no filter bubble, no distractions. Everyone works with the same, reliable knowledge base.',
      },
      grounded: {
        title: 'The AI stays within the article',
        body: 'The reading assistant searches exclusively within the selected article. It doesn’t pull information from anywhere else on the internet and it doesn’t invent facts (i.e. hallucinate). This makes the results reliable and traceable.',
      },
      active: {
        title: 'A counter-model to the “prompt trap”',
        body: 'Instead of simply being handed a ready-made answer, learners work actively with an approved text. They read, ask targeted questions, check evidence, and connect knowledge. This kind of research and media competency is a core foundation in international frameworks such as PISA 2029.',
      },
      equity: {
        title: 'Educational equity',
        body: 'Because complex articles become linguistically accessible, students at all levels, regardless of their reading and language proficiency, can access high-quality knowledge.',
      },
      gifted: {
        title: 'Support for gifted learners',
        body: 'High performers benefit too. Thanks to the choice of language level, they can choose a version that is much closer to the original by selecting a more demanding level, dive deeper into a topic via the sources and cross-references, and pursue further questions with the reading assistant.',
      },
      oer: {
        title: 'Open educational resources (OER)',
        body: 'Wikipedia content is available under free licences. It can be reused for presentations, projects, and in the students’ own work.',
      },
      images: {
        title: 'Images under Creative Commons licence',
        body: 'Wikimedia Commons provides legally safe-to-use images which is ideal for helping learners understand image rights instead of just copying random images from the web.',
      },
      privacy: {
        title: 'Anonymous and privacy friendly',
        body: 'ai-pedia can be used without a login and without providing any personal data which makes it safe and easy to use in the classroom.',
      },
    },
    summaryTitle: 'In short',
    summary:
      'ai-pedia doesn’t just provide an answer, it provides a vetted, evidence-based, and traceable foundation, training students in the skills that matter most in the age of AI: conscious handling of information and the ability to critically assess sources.',
  },
  pisa: {
    title: 'ai-pedia in the Context of PISA 2029 and the AILit Framework',
    introduction:
      'A new domain is being added to the PISA 2029 assessment: Media and Artificial Intelligence Literacy (MAIL). This interdisciplinary, forward-looking field tests competencies that are crucial when dealing with AI and media.',
    framework:
      'The international AI competency framework “Empowering Learners for the Age of AI” (AILit Framework, OECD / European Union, 2026), which is preparing the ground for the PISA 2029 assessment, identifies several key abilities. Learners should:',
    items: {
      verify: {
        title: 'Check AI results instead of simply accepting them',
        body: 'The framework requires learners to question AI results and check them for accuracy and relevance, using trustworthy primary and secondary sources. ai-pedia provides exactly this kind of curated source, complete with evidence.',
      },
      hallucinations: {
        title: 'Recognize hallucinations',
        body: 'The framework warns against hallucination, misinformation, and manipulation by AI. Since ai-pedia’s assistant only works within the vetted article and displays its source, learners can directly practice recognizing such errors by comparing it with general AI research tools.',
      },
      overtrust: {
        title: 'Avoid over-reliance',
        body: 'According to the framework, offloading thinking processes onto AI leads to “metacognitive laziness” and weakens critical thinking. ai-pedia keeps learners actively engaged. They have to read, ask targeted questions, and check evidence rather than passively accepting ready-made answers.',
      },
      judgement: {
        title: 'Preserve human judgment',
        body: 'Learners should develop a sense of when AI adds value, when human judgment, creativity, and knowledge should take precedence and when it’s better to forgo AI altogether. Humans must steer AI, not the other way around. ai-pedia makes this boundary visible and tangible.',
      },
    },
    conclusionTitle: 'Conclusion: The Rationale',
    conclusion:
      'All of these abilities can be learnt by using ai-pedia in everyday classroom activities. This is the kind of future-oriented competency that the OECD, the EU, and PISA will require starting in 2029. Learners will have to check AI answers against vetted sources instead of trusting them blindly which in turn protects them against fake news, disinformation, and filter bubbles.',
  },
  lesson: {
    title: 'Procedure for the ai-pedia Introductory Lesson',
    duration: 'Around 50 minutes',
    introductionBefore:
      'The following lesson familiarizes the class with ai-pedia. It can be applied to any subject. Here we’re using the Wikipedia article “Tree”, which works well',
    treeLinkLabel: 'ai-pedia.ch/article/en/Tree',
    treeLinkUrl: 'https://ai-pedia.ch/article/en/Tree',
    introductionAfter:
      'but you can choose any article that fits the topic you’re teaching. The first goal is for learners to try out the two central functions: “Simplify text” and “Ask questions”, while the second is to ensure they understand why ai-pedia is deliberately used instead of a search engine or a general-purpose AI chatbot like ChatGPT, which gathers its answers from across the entire internet.',
    steps: {
      one: {
        number: '1',
        title: 'Introduction: Why Not Just Google It?',
        meta: 'approx. 5 min · Whole class',
        body: 'Initial discussion to gather ideas: Where do you normally get information from? What’s the catch with a quick Google or AI answer? (Possible points: unclear source, advertising, sometimes made up.) Announce: Today you’ll get to know a tool that works differently.',
      },
      two: {
        number: '2',
        title: 'Discovering “Simplify Text”',
        meta: 'approx. 10 min · Individual/pair work',
        body: 'Learners open ai-pedia and call up a given article. Task: Click the “Simplify text” icon and try out both options. The original Wikipedia article always remains accessible. “Show original article” opens it within ai-pedia, while “View on Wikipedia” takes you directly to the Wikipedia website.',
        gradeTitle: 'Option “by school grade”',
        gradeBody:
          'The article becomes a compact summary and the original chapter structure is dropped. Three levels let you set how much it is shortened and simplified: Level 1 (simple), Level 2 (medium), and Level 3 (in-depth).',
        extraTitle: 'Extra task',
        extraBody:
          'Compare the three levels “simple,” “medium,” and “in-depth.” What changes from level to level? Consider text length, vocabulary, and level of detail.',
        languageTitle: 'Option “by language level”',
        languageBody:
          'The article’s structure stays the same so the chapters remain in the same order. However, because the language is simplified, some headings change. “Definition,” for example, becomes “What is a tree?” and “Physiology” becomes “How trees live.” The text becomes less academic and easier to read but it remains factually correct and continues to draw on scientific sources.',
      },
      three: {
        number: '3',
        title: 'Checking Comprehension: “Quiz” and “Key Terms”',
        meta: 'approx. 5 min · Individual/pair work',
        body: 'In the simplified view, ai-pedia offers two aids for text comprehension. Task: Try out both.',
        glossaryTitle: '“Key Terms”',
        glossaryBody: 'This briefly explains the most important keywords from the text.',
        quizTitle: '“Quiz”',
        quizBody:
          'Then use “Quiz” to check your understanding. Answer the questions about the text and see what you’ve already grasped and what you should read again.',
      },
      four: {
        number: '4',
        title: 'School Grade or Language Level – When to Use Which?',
        meta: 'approx. 8 min · Whole class / pair work',
        body: 'Make the difference clear and let learners decide:',
        gradeTitle: '“By school grade”',
        gradeBody:
          '(including the “Quiz” and “Key Terms” features) is suitable when you need a quick overview or a compact summary, for example, to prepare a presentation or get an initial introduction to a topic.',
        languageTitle: '“By language level”',
        languageBody:
          'is suitable when you want to work through the entire article with its full structure, but the language is too difficult.',
        taskTitle: 'Task (pair work)',
        taskBody:
          'Discuss in pairs: When does “by language level” make more sense and when does “by school grade”? Also think about when using both together might be helpful, for example, first “by school grade” for an overview and then “by language level” to work through the article in depth.',
      },
      five: {
        number: '5',
        title: '“Ask Questions”: The Reading Assistant',
        meta: 'approx. 8 min · Individual/pair work',
        body: 'Learners open “Ask questions” and test ai-pedia’s reading assistant with the tree article using a small experiment.',
        trickTitle: 'The trick question',
        trickBody:
          'First ask the chatbot a cheeky question that definitely doesn’t appear in the tree article. For example, “When was the first tree planted on the moon?” What does it answer?',
        comparisonTitle: 'The Google comparison',
        comparisonBody: 'Then type the same question into Google or another search engine and compare: What do you get there?',
        insightTitle: 'Insight',
        insightBody:
          'ai-pedia’s reading assistant only searches the selected article. Given that the tree article says nothing about trees on the moon, it doesn’t make anything up but instead points out that there is no information on this.',
        moonBefore:
          'Google’s AI and other search engines, on the other hand, provide answers from across the whole web. So you will actually find something on the topic of “Moon tree.” But look closely. This answer, too, is based on a Wikipedia article',
        moonLinkLabel: '“Moon tree”',
        moonLinkUrl: 'https://en.wikipedia.org/wiki/Moon_tree',
        moonAfter: 'Learners can now analyze this article with ai-pedia.',
        languageVersions: 'Language versions',
        languageLinks: {
          deLabel: 'German',
          deUrl: 'https://de.wikipedia.org/wiki/Mondbaum',
          frLabel: 'French',
          frUrl: 'https://fr.wikipedia.org/wiki/Moon_tree',
          itLabel: 'Italian',
          itUrl: 'https://it.wikipedia.org/wiki/Alberi_della_luna',
          enLabel: 'English',
          enUrl: 'https://en.wikipedia.org/wiki/Moon_tree',
        },
        realTitle: '“Real” questions',
        realBody:
          'Now ask two genuine questions on the topic. Pay attention to the sources. For every answer, the reading assistant shows you the evidence from the original Wikipedia article on which the information is based. Source references are highlighted in colour within the text and the original Wikipedia reference numbers remain visible. Click on a source and check: Does the answer match the cited passage?',
      },
      six: {
        number: '6',
        title: 'Why ai-pedia and Not an AI Summary?',
        meta: 'approx. 8 min · Whole class',
        body: 'Make the added value clear. Use the talking points for students (see below) as a basis for a discussion or a matching task. Core message: a chatbot always gives you an answer, ready-made and convincingly phrased. That’s exactly where the danger lies: you accept it quickly, without checking the sources. ai-pedia, on the other hand, provides a vetted, evidence-based answer that you can check yourself. And in doing so, you learn something no one can ever take away from you: how to assess sources.',
      },
      seven: {
        number: '7',
        title: 'Privacy – Your Data Belongs to You',
        meta: 'approx. 3 min · Whole class',
        body: 'State this as a rule: Using ai-pedia is anonymous, no login and no personal data are required. And as everywhere on the internet, the same applies to ai-pedia: never disclose personal data, neither your own nor your classmates’. This means no full name, no address, no phone number and no private details. This kind of information is completely unnecessary for researching or asking questions.',
      },
      eight: {
        number: '8',
        title: 'Wrap-up',
        meta: 'approx. 3 min · Individual work',
        body: 'Short reflection: What can ai-pedia do that a quick search can’t? Each learner formulates one sentence: “I use ai-pedia when …”',
      },
    },
  },
  studentArguments: {
    audience: 'For students',
    title: 'Talking Points for Students',
    introduction: 'Why use ai-pedia instead of just Googling or asking an AI? Seven reasons to pass on:',
    reasons: {
      reliable: {
        number: '1',
        title: 'Reliable',
        body: 'You work with genuine, human-checked texts, not with an answer that might be made up.',
      },
      verifiable: {
        number: '2',
        title: 'Verifiable',
        body: 'For every piece of information you see the source and can check for yourself whether it’s correct.',
      },
      suitable: {
        number: '3',
        title: 'Tailored to you',
        body: 'The text comes in your language and at your level, you no longer struggle with a difficult original.',
      },
      reusable: {
        number: '4',
        title: 'Fair to use',
        body: 'Images and texts are under free licences, you can use them for your presentation as long as you cite the source.',
      },
      focused: {
        number: '5',
        title: 'Focused',
        body: 'The AI stays within the article, no scraping together bits from half the internet, no advertising, and no algorithm trying to distract you.',
      },
      capable: {
        number: '6',
        title: 'You get better',
        body: 'You learn to check sources, perhaps the most important skill in the age of AI.',
      },
      future: {
        number: '7',
        title: 'Future-proof',
        body: 'Even the major PISA assessment will test, starting in 2029, whether you can check AI answers instead of simply believing them. With ai-pedia, you practise exactly that.',
      },
    },
    summaryTitle: 'The Key Point in One Sentence',
    summary:
      'AI can be wrong, confidently, and without showing it. Knowledge that has been checked by humans and backed by sources, on the other hand, you can verify yourself. That’s why, with ai-pedia, you learn from vetted Wikipedia knowledge instead of simply accepting everything an AI says. This doesn’t make you slower, it makes you more confident and smarter.',
  },
  implementationNote: {
    title: 'Note on implementation',
    body: 'This introductory lesson is deliberately designed to be subject-independent. You can use any Wikipedia article – ideally one that fits your current teaching topic. As is always the case with internet research (see the section on child protection), careful supervision of learners is important. Research on ai-pedia is no different since it accesses original, unfiltered Wikipedia articles.',
  },
  sources: {
    title: 'Sources',
    ailitLabel: 'AI Literacy Framework (OECD / European Union)',
    ailitLinkLabel: 'ailiteracyframework.org',
    ailitUrl: 'https://ailiteracyframework.org/',
    ailitAfter: 'available in 24 languages.',
    pisaLabel: 'PISA 2029 – Media and Artificial Intelligence Literacy (OECD)',
    pisaLinkLabel: 'oecd.org/…/pisa-2029-media-and-artificial-intelligence-literacy',
    pisaUrl: 'https://www.oecd.org/en/about/projects/pisa-2029-media-and-artificial-intelligence-literacy.html',
    pisaAfter: 'the document is available in English and French.',
  },
};
