type SupportedLocale = 'de' | 'en' | 'fr' | 'it' | 'rm';

const WIKIPEDIA_LANGUAGE_LABELS: Record<SupportedLocale, Record<string, string>> = {
  de: {
    azb: 'Südaserbaidschanisch',
    'bat-smg': 'Samogitisch',
    'be-tarask': 'Belarussisch (Tarask)',
    'be-x-old': 'Belarussisch (Tarask)',
    btm: 'Mandailing',
    cdo: 'Min Dong',
    dty: 'Doteli',
    eml: 'Emiliano-Romagnolisch',
    'fiu-vro': 'Võro',
    gcr: 'Guayana-Kreolisch',
    kbp: 'Kabiyè',
    lld: 'Ladinisch',
    nan: 'Min Nan',
    'nds-nl': 'Niedersächsisch (Niederlande)',
    olo: 'Livvisch',
    rki: 'Rakhine',
    simple: 'Einfaches Englisch',
    'sr-el': 'Serbisch (Lateinisch)',
    szy: 'Sakizaya',
    szl: 'Schlesisch',
    yue: 'Kantonesisch',
    'zh-classical': 'Klassisches Chinesisch',
    'zh-min-nan': 'Min Nan',
    'zh-yue': 'Kantonesisch',
  },
  en: {
    azb: 'South Azerbaijani',
    'bat-smg': 'Samogitian',
    'be-tarask': 'Belarusian (Tarask)',
    'be-x-old': 'Belarusian (Tarask)',
    btm: 'Mandailing',
    cdo: 'Min Dong Chinese',
    dty: 'Doteli',
    eml: 'Emiliano-Romagnol',
    'fiu-vro': 'Võro',
    gcr: 'Guianan Creole',
    kbp: 'Kabiye',
    lld: 'Ladin',
    nan: 'Min Nan Chinese',
    'nds-nl': 'Low Saxon (Netherlands)',
    olo: 'Livvi-Karelian',
    rki: 'Rakhine',
    simple: 'Simple English',
    'sr-el': 'Serbian (Latin)',
    szy: 'Sakizaya',
    szl: 'Silesian',
    yue: 'Cantonese',
    'zh-classical': 'Classical Chinese',
    'zh-min-nan': 'Min Nan Chinese',
    'zh-yue': 'Cantonese',
  },
  fr: {
    azb: 'Azéri du Sud',
    'bat-smg': 'Samogitien',
    'be-tarask': 'Biélorusse (tarachkevitsa)',
    'be-x-old': 'Biélorusse (tarachkevitsa)',
    btm: 'Mandailing',
    cdo: 'Chinois min dong',
    dty: 'Doteli',
    eml: 'Émilien-romagnol',
    'fiu-vro': 'Võro',
    gcr: 'Créole guyanais',
    kbp: 'Kabiye',
    lld: 'Ladin',
    nan: 'Chinois min nan',
    'nds-nl': 'Bas saxon (Pays-Bas)',
    olo: 'Carélien livvi',
    rki: 'Rakhine',
    simple: 'Anglais simple',
    'sr-el': 'Serbe (latin)',
    szy: 'Sakizaya',
    szl: 'Silésien',
    yue: 'Cantonais',
    'zh-classical': 'Chinois classique',
    'zh-min-nan': 'Chinois min nan',
    'zh-yue': 'Cantonais',
  },
  it: {
    azb: 'Azero meridionale',
    'bat-smg': 'Samogitico',
    'be-tarask': 'Bielorusso (tarask)',
    'be-x-old': 'Bielorusso (tarask)',
    btm: 'Mandailing',
    cdo: 'Cinese min dong',
    dty: 'Doteli',
    eml: 'Emiliano-romagnolo',
    'fiu-vro': 'Võro',
    gcr: 'Creolo della Guyana',
    kbp: 'Kabiye',
    lld: 'Ladino',
    nan: 'Cinese min nan',
    'nds-nl': 'Basso sassone (Paesi Bassi)',
    olo: 'Careliano livvi',
    rki: 'Rakhine',
    simple: 'Inglese semplice',
    'sr-el': 'Serbo (latino)',
    szy: 'Sakizaya',
    szl: 'Slesiano',
    yue: 'Cantonese',
    'zh-classical': 'Cinese classico',
    'zh-min-nan': 'Cinese min nan',
    'zh-yue': 'Cantonese',
  },
  rm: {
    azb: 'Aserbaidschanic dal sid',
    'bat-smg': 'Samogitian',
    'be-tarask': 'Bieloruss (tarask)',
    'be-x-old': 'Bieloruss (tarask)',
    btm: 'Mandailing',
    cdo: 'Chinais min dong',
    dty: 'Doteli',
    eml: 'Emilian-romagnol',
    'fiu-vro': 'Võro',
    gcr: 'Creol da Guyana',
    kbp: 'Kabiye',
    lld: 'Ladin',
    nan: 'Chinais min nan',
    'nds-nl': 'Bass saxon (Pajais Bass)',
    olo: 'Carelian livvi',
    rki: 'Rakhine',
    simple: 'Englais simpel',
    'sr-el': 'Serb (latin)',
    szy: 'Sakizaya',
    szl: 'Silesian',
    yue: 'Cantonais',
    'zh-classical': 'Chinais classic',
    'zh-min-nan': 'Chinais min nan',
    'zh-yue': 'Cantonais',
  },
};

function normalizeLocale (locale: string): SupportedLocale {
  const localeRoot = locale.toLowerCase().split(/[-_]/)[0];
  if (localeRoot === 'de' || localeRoot === 'fr' || localeRoot === 'it' || localeRoot === 'rm') {
    return localeRoot;
  }
  return 'en';
}

export function getWikiLanguageLabel (code: string, locale: string): string | undefined {
  const normalizedCode = code.toLowerCase().replace(/_/g, '-');
  const normalizedLocale = normalizeLocale(locale);
  return WIKIPEDIA_LANGUAGE_LABELS[normalizedLocale][normalizedCode] ?? WIKIPEDIA_LANGUAGE_LABELS.en[normalizedCode] ?? WIKIPEDIA_LANGUAGE_LABELS.de[normalizedCode];
}
